name: traveling_partner
description: "Traveling partner project app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # routing
  auto_route: ^7.9.0

  # database management 
  cloud_firestore: ^4.15.9

  # app icons
  cupertino_icons: ^1.0.6 

  # date picker 
  date_picker_plus: ^3.0.0

  # object equality
  equatable: ^2.0.5

  # Authentication
  firebase_auth: ^4.17.9

  # firebase
  firebase_core: ^2.27.1

  # state management
  flutter_bloc: ^8.1.3

  # dependency injection
  get_it: ^7.6.7

  # sign in with google
  google_sign_in: ^6.2.1

  # caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # json
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # animation
  lottie: ^3.1.0

  # svg 
  flutter_svg: ^2.0.10+1

  # sharing
  share_plus: ^7.2.2

  # mail sender
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # router code generator
  auto_route_generator: ^7.3.2

  # linter
  flutter_lints: ^3.0.0

  # app icon
  flutter_launcher_icons: ^0.13.1

  # splash screen
  flutter_native_splash: ^2.4.0

# Splash Screen
flutter_native_splash:
  image: assets/splash/splash.png
  image_dark: assets/splash/splash.png
  color: "#009000"
  color_dark: "#009000"

  web: false

# App icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/animation/
    - assets/svg/
    - assets/splash/

  fonts:
    - family: CabinRegular
      fonts:
        - asset: assets/fonts/cabin_regular.ttf
