// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, public_member_api_docs, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOB_L6mrg0EvmewKxOwMgFxoaoWlQYXmU',
    appId: '1:210723450216:web:f8c70c3291c7a8f3bc7add',
    messagingSenderId: '210723450216',
    projectId: 'traveling-partner',
    authDomain: 'traveling-partner.firebaseapp.com',
    storageBucket: 'traveling-partner.appspot.com',
    measurementId: 'G-1XDJ6DNTQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANmcE-MCB7NrqpzynqA5ZFdNObUIv9i7U',
    appId: '1:210723450216:android:5b7f87a0cc9bdb3bbc7add',
    messagingSenderId: '210723450216',
    projectId: 'traveling-partner',
    storageBucket: 'traveling-partner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXoeO-8cwvf2JKTXiQOiBN4O4EWT3c5kk',
    appId: '1:210723450216:ios:ce4519a4e228a590bc7add',
    messagingSenderId: '210723450216',
    projectId: 'traveling-partner',
    storageBucket: 'traveling-partner.appspot.com',
    iosBundleId: 'com.example.travelingPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXoeO-8cwvf2JKTXiQOiBN4O4EWT3c5kk',
    appId: '1:210723450216:ios:ef9569bb338610bbbc7add',
    messagingSenderId: '210723450216',
    projectId: 'traveling-partner',
    storageBucket: 'traveling-partner.appspot.com',
    iosBundleId: 'com.example.travelingPartner.RunnerTests',
  );
}
